/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as GoalsIndexRouteImport } from './routes/goals/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ResourcesIdRouteImport } from './routes/resources/$id'
import { Route as GoalsGoalIdTimelineRouteImport } from './routes/goals/$goalId/timeline'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIdRoute = ResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdTimelineRoute = GoalsGoalIdTimelineRouteImport.update({
  id: '/goals/$goalId/timeline',
  path: '/goals/$goalId/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/goals/$goalId/timeline': typeof GoalsGoalIdTimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/goals': typeof GoalsIndexRoute
  '/library': typeof LibraryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/goals/$goalId/timeline': typeof GoalsGoalIdTimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/goals/$goalId/timeline': typeof GoalsGoalIdTimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/resources/$id'
    | '/dashboard/'
    | '/goals/'
    | '/library/'
    | '/api/auth/$'
    | '/goals/$goalId/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/resources/$id'
    | '/dashboard'
    | '/goals'
    | '/library'
    | '/api/auth/$'
    | '/goals/$goalId/timeline'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/resources/$id'
    | '/dashboard/'
    | '/goals/'
    | '/library/'
    | '/api/auth/$'
    | '/goals/$goalId/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ResourcesIdRoute: typeof ResourcesIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  GoalsIndexRoute: typeof GoalsIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  GoalsGoalIdTimelineRoute: typeof GoalsGoalIdTimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/': {
      id: '/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$id': {
      id: '/resources/$id'
      path: '/resources/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof ResourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/$goalId/timeline': {
      id: '/goals/$goalId/timeline'
      path: '/goals/$goalId/timeline'
      fullPath: '/goals/$goalId/timeline'
      preLoaderRoute: typeof GoalsGoalIdTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ResourcesIdRoute: ResourcesIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  GoalsIndexRoute: GoalsIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  GoalsGoalIdTimelineRoute: GoalsGoalIdTimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
